<?php
/**
 * @var $block Magenest\GiftRegistry\Block\Registry\ListGift
 */
$link = $block->getViewFileUrl('/');
$baseUrl = $block->getBaseUrlEvent();
$listEvent = $block->getListEvent();
$backgroundImg = $block->getBackgroundImage();
$style = $backgroundImg != null ? 'style="background-image: url(' . $backgroundImg . ')"' : "";
$title = $block->getTitle();
?>
<div class="gift_view" <?= $style ?>>
  <div class="gift_search_wrapper">
    <div class="gift-view-container">
      <div class="create-a-registry">
        <a href="<?= $block->getViewGiftRegistryUrl(); ?>">
          <button class="create-registry">
                        <span>
                            <?php
                            if ($block->isLoggedIn()):
                              echo __('View my gift registry');
                            else:
                              echo __('Create a Registry');
                            endif;
                            ?>
                        </span>
          </button>
        </a>
      </div>
      <div class="gift-search-content">
        <h2 class="gift_h2"><?= __('Search Gift Registry') ?></h2>
        <div class="gift_search_container">
          <form id="gift_search_form" data-mage-init='{"validation":{}}' class="gift_search_form" method="GET"
                action="<?= $block->getListSearchUrl() ?>">
            <!--                        <input name="form_key" type="hidden" value="-->
            <?php //echo $block->getFormKey()?><!--"/>-->
            <div class="select-type">
              <div class="select-box">
                <select id="type-selected" name="type" class="list-gift" title="Select Event Type">
                  <option selected value="all"><?= __("All Type") ?></option>
                  <?php foreach ($listEvent as $event): ?>
                    <option value="<?= $event->getEventType() ?>"><?= $block->escapeHtml($event->getEventTitle()) ?></option>
                  <?php endforeach; ?>
                </select>
              </div>
              <div class="select-box">
                <select id="filter-selected" name="filter" class="list-gift" title="Select Filter">
                  <option id="filter-title" <?= $title != "" ? "selected" : "" ?>
                          value="1"><?= __("Filter By Title") ?></option>
                  <option id="filter-name" <?= $title == "" ? "selected" : "" ?>
                          value="2"><?= __("Filter By Name") ?></option>
                </select>
              </div>
            </div>
            <?php if ($title != ""): ?>
              <div id="search-name-wrapper" class="search-name-wrapper">

              </div>
              <div id="search-title-wrapper" class="search-title-wrapper">
                <div class="field">
                  <input id="title" name="t" class="search_input" data-validate="{required:true}" type="text"
                         placeholder="<?= __('Title') ?>">
                </div>
              </div>
            <?php else: ?>
              <div id="search-name-wrapper" class="search-name-wrapper">
                <div class="field">
                  <input id="event_fn" name="fn" class="search_input" data-validate="{required:true}" type="text"
                         placeholder="<?= __('First Name') ?>">
                </div>
                <div class="field">
                  <input id="event_ln" name="ln" class="search_input" data-validate="{required:true}" type="text"
                         placeholder="<?= __('Last Name') ?>">
                </div>
              </div>
              <div id="search-title-wrapper" class="search-title-wrapper">

              </div>
            <?php endif; ?>
            <div class="btn_wrapper">
              <button type="button" id="search_registry_submit_btn"><?= __('Search') ?></button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="registry-container">
  <div class="all_gift_title"><h2><?= __('Filter By Event Type') ?></h2></div>
  <div class="list_registry">
    <?php foreach ($listEvent as $event): ?>
      <?php $eventType = $event->getData('event_type') ?>
      <?php if ($event->getData('status') == 1): ?>
        <span class="each_gift">
                    <div class="each-gift-type">
                        <a href="<?= $block->getGiftUrl($event->getData('event_type')) ?>" class="link-img">
                        <?php
                        $thumbnail = $event->getData('thumnail');
                        if ($thumbnail != ''):
                          $src = $block->getUrlImage($thumbnail);
                          ?>
                          <img src="<?= $src ?>">
                        <?php
                        else:
                          ?>
                          <img src="<?= $link . '/Magenest_GiftRegistry/images/gift-item.jpeg'; ?>">
                        <?php
                        endif;
                        ?>
                            </a>
                        <div class="each-gift-detail">
                            <div class="gift_title">

                                <a href="<?= $block->getGiftUrl($event->getData('event_type')) ?>">
                                    <h3><?= $block->escapeHtml($event->getData('event_title')); ?></h3>
                                </a>
                            </div>
                            <?php if ($event->getData('description') != ''): ?>
                              <div class="gift-description">
                                    <span><?= strlen($event->getData('description')) > 100 ? substr($block->escapeHtml($event->getData('description')),0,100).'...':$block->escapeHtml($event->getData('description'))?></span>
                                </div>
                            <?php endif; ?>
                    </div>
                    </div>

          </a>
            </span>
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magenest_GiftRegistry/js/giftregistry/show-giftregistry": {
                "actionUrl" : {
                    "customerLogin":"<?= $block->getUrl('customer/account/login')?>",
                    "registry": "<?= $block->getUrl("gift_registry/index/registry")?>+?isAjax=true",
                    "search": "<?= $block->getListSearchUrl() ?>?isAjax=true"
                },
                "eventType": "<?= "" ?>",
                "registryId": "<?= "" ?>"
            }
        }
    }

</script>
