<?php
/** @var \Magenest\GiftRegistry\Block\Guest\ListSearch $block */
$keyWords = $block->getListRegistry();
$link = $block->getViewFileUrl('/');
$listEvent = $block->getListEvent();
$backgroundImg = $block->getBackgroundImage();
$style = $backgroundImg != null ? 'style="background-image: url(' . $backgroundImg . ')"' : "";
$title = $block->getTitle();
?>
<div class="gift_view" <?= $style ?>>
  <div class="gift_search_wrapper">
    <div class="gift-view-container">
      <div class="create-a-registry">
        <a href="<?= $block->getViewGiftRegistryUrl(); ?>">
          <button class="create-registry">
            <span>
              <?php
              if ($block->isLoggedIn()):
                echo __('View my gift registry');
              else:
                echo __('Create a Registry');
              endif;
              ?>
            </span>
          </button>
        </a>
      </div>
      <div class="gift-search-content">
        <h2 class="gift_h2"><?= __('Search Gift Registry') ?></h2>
        <div class="gift_search_container">
          <form id="gift_search_form" data-mage-init='{"validation":{}}' class="gift_search_form" method="GET"
                action="<?= $block->getListSearchUrl() ?>">
            <input name="type" type="hidden" value="<?= $block->getTypeEvent(); ?>"/>
            <div class="select-type">
              <div class="select-box">
                <?php
                ?>
                <select id="filter-selected" name="filter" class="list-gift" title="Select Filter">
                  <option id="filter-title" <?= $title != "" ? "selected" : "" ?>
                          value="1"><?= __("Filter By Title") ?></option>
                  <option id="filter-name" <?= $title == "" ? "selected" : "" ?>
                          value="2"><?= __("Filter By Name") ?></option>
                </select>
              </div>
            </div>
            <?php if ($title != ""): ?>
              <div id="search-name-wrapper" class="search-name-wrapper">
              </div>
              <div id="search-title-wrapper" class="search-title-wrapper">
                <div class="field">
                  <input id="title" name="t" class="search_input" data-validate="{required:true}" type="text"
                         placeholder="<?= __('Title') ?>">
                </div>
              </div>
            <?php else: ?>
              <div id="search-name-wrapper" class="search-name-wrapper">
                <div class="field">
                  <input id="event_fn" name="fn" class="search_input" data-validate="{required:true}" type="text"
                         placeholder="<?= __('First Name') ?>">
                </div>
                <div class="field">
                  <input id="event_ln" name="ln" class="search_input" data-validate="{required:true}" type="text"
                         placeholder="<?= __('Last Name') ?>">
                </div>
              </div>
              <div id="search-title-wrapper" class="search-title-wrapper">

              </div>
            <?php endif; ?>

            <div class="btn_wrapper">
              <button type="button" id="search_registry_submit_btn"><?= __('Search') ?></button>
            </div>
          </form>
        </div>
      </div>
      <div class="reset-action">
        <a href="<?= $block->getGiftRegistryPageUrl(); ?>">
          <button class="action reset"><?= __("Reset") ?></button>
        </a>
      </div>
    </div>
  </div>
</div>
<div class="list-registry">
  <div class="list-registry-container">
    <div class="list-registry-content">
      <div class="search-message">
        <?php if ($block->isFilterByName()): ?>
          <?php if (count($keyWords) == 0) { ?>
            <div class="no-data">
              <span
                class="empty-text"><?= __("We couldn't find any record(s) with '" . htmlspecialchars($block->getFirstname(), ENT_QUOTES, 'UTF-8') . "' - '" . htmlspecialchars($block->getLastname(), ENT_QUOTES, 'UTF-8') . "'!") ?></span>
            </div>

          <?php } else { ?>
            <div class="no-data">
              <span
                class="empty-text"><?= __("We found " . count($keyWords) . " record(s) with '" . htmlspecialchars($block->getFirstname(), ENT_QUOTES, 'UTF-8') . "' - '" . htmlspecialchars($block->getLastname(), ENT_QUOTES, 'UTF-8') . "'") ?></span>
            </div>
          <?php } ?>
        <?php else : ?>
          <?php if (count($keyWords) == 0) { ?>
            <div class="no-data">
              <span
                class="empty-text"><?= __("We couldn't find any record(s) with title '" . htmlspecialchars($block->getTitle(), ENT_QUOTES, 'UTF-8') . "'!") ?></span>
            </div>
          <?php } else { ?>
            <div class="no-data">
              <span
                class="empty-text"><?= __("We found " . count($keyWords) . " record(s) with title '" . htmlspecialchars($block->getTitle(), ENT_QUOTES, 'UTF-8') . "'!") ?></span>
            </div>
          <?php } ?>
        <?php endif; ?>
      </div>
      <div class="gift-type-list">
        <ul class="gift-type-items">
          <?php
          $i = 0;
          foreach ($keyWords as $keyWord) {
            $infors = $block->getInforEvent($keyWord['giftregistry_id']);
            if (count($infors)) {
              $i++;
              ?>
              <li class="gift-type-item">
                <div class="gift-type-info">
                  <?php
                  foreach ($infors as $infor):
                  ?>
                  <div class="gift-image">
                    <a href="<?= $block->getPreviewUrl($infor->getData('gift_id'), $infor->getData('type')) ?>"
                       class="link-image">
                      <?php if ($infor->getData('image') == ''): ?>
                        <img src="<?= $link . '/Magenest_GiftRegistry/images/thumbnail-default.jpg' ?>"/>
                      <?php
                      else:
                        $path = $block->getImageUrl($infor->getData('image'));
                        ?>
                        <img src="<?= $path; ?>"/>
                      <?php endif; ?>
                    </a>
                    <div class="gift-type-hover">
                      <div class="gift-type-name">
                        <a href="<?= $block->getPreviewUrl($infor->getData('gift_id'), $infor->getData('type')) ?>">
                          <?php if (strlen($infor->getData('title')) <= 100) {
                            echo $block->escapeHtml($infor->getData('title'));
                          } else {
                            echo substr($block->escapeHtml($infor->getData('title')), 0, 100) . '...';
                          } ?>
                        </a>
                      </div>
                      <div class="gift-type">
                        <?= __('Type: ') ?>
                        <?= $infor->getData('type') ?>
                      </div>
                      <div class="gift-type-description">
                        <?php if (strlen($infor->getData('description')) < 100) {
                          echo html_entity_decode($infor->getData('description'));
                        } else {
                          $text = substr($infor->getData('description'), 0, 25);
                          echo html_entity_decode($text . '<p>...</p>');
                        } ?>
                      </div>
                      <div class="gift-type-detail">
                        <div class="gift-registry-date">
                          <?= $infor->getData('date'); ?>
                        </div>
                        <div class="gift-registry-location">
                          <?= $block->escapeHtml($infor->getData('location')); ?>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>
                <?php endforeach; ?>
              </li>
            <?php }
          } ?>
        </ul>
      </div>
    </div>
  </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magenest_GiftRegistry/js/giftregistry/show-giftregistry": {
                "actionUrl" : {
                    "customerLogin":"<?= $block->getUrl('customer/account/login')?>",
                    "registry": "<?= $block->getUrl("gift_registry/index/registry")?>+?isAjax=true",
                    "search": "<?= $block->getListSearchUrl() ?>?isAjax=true"
                },
                "eventType": "<?= "" ?>",
                "registryId": "<?= "" ?>"
            }
        }
    }
</script>
