<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<style>
    ._required > .admin__field-label span:after {
        position: unset !important
    }
</style>
<?php
/**
 * Template for \Magento\Backend\Block\Widget\Grid
 *  getId()
 *  getCollection()
 *  getColumns()
 *  getPagerVisibility()
 *  getVarNamePage()
 */

/**
 * @var \Magenest\GiftRegistry\Block\Adminhtml\Grid $block
 */
$numColumns = sizeof($block->getColumns());
$addressArr = $block->getCustomerAddress();
$eventTitle = $block->getEventType();
$editEvent = $block->getGiftRegistry();
?>
<?php if ($block->getCollection()): ?>
    <?php if ($block->canDisplayContainer()): ?>
    <div id="popup" hidden>
        <div class="admin__field _required" >

            <label class="admin__field-label">
                <span>First Name</span>
            </label>

            <div class="admin__field-control">
                <input type="text" title="<?= __("First Name")  ?>"
                       id="firstName" class="admin__control-text" placeholder="First Name">
            </div>
        </div>
        <div class="admin__field _required">

            <label class="admin__field-label">
                <span>Last Name</span>
            </label>

            <div class="admin__field-control">
                <input type="text" title="<?= __("Last name")  ?>"
                       id="lastName" class="admin__control-text" placeholder="Last Name">
            </div>
        </div>
        <div class="admin__field _required">

            <label class="admin__field-label">
                <span>Email</span>
            </label>

            <div class="admin__field-control">
                <input type="email" title="<?= __('Email')?>"
                       id="email" class="admin__control-text" placeholder="Email">
            </div>
        </div>
        <div class="admin__field _required">

            <label class="admin__field-label">
                <span>Privacy mode</span>
            </label>

            <div class="control">
                <select id="select-privacy" name="privacy" style="border: 1px solid #adadad; width: 100%; height: 35px; background: white">
                    <option value=""><?= __('Privacy Mode')  ?></option>
                    <option value="public"> <?php  echo __("Public")  ?></option>
                </select>
            </div>
        </div><br/>
        <div class="field choice field-showinsearch">
            <input type="checkbox" id="show_in_search" name="show_in_search" class="checkbox" title="<?= __("Show in search result") ?>" >
            <label  class ="label" for="show_in_search"><?= __("Show in search result") ?></label>
        </div> <br/>

        <div class="admin__field _required">

            <label class="admin__field-label">
                <span>Event Type</span>
            </label>

            <div class="admin__field-control">
                <select name="shipping_address" id="event_type" style="border: 1px solid #adadad; width: 100%; height: 35px; background: white">
                    <option value=""><?= __('Event Type')  ?></option>
                    <?php if ($eventTitle) {
                        foreach ($eventTitle as $event) {
                            ?>
                            <option value="<?= $event['event_type'] ?>"><?= $event['event_type'] ?></option>
                        <?php  } }?>
                </select>
            </div>
        </div>

        <div class="admin__field _required">

            <label class="admin__field-label">
                <span>Event's title</span>
            </label>

            <div class="admin__field-control">
                <input type="text" class="admin__control-text" name="title"  placeholder="Event's title" id="event_title"/>
            </div>
        </div>

        <div class="admin__field _required">

            <label class="admin__field-label">
                <span>Date</span>
            </label>

            <div class="admin__field-control">
                <input id="date" type="date" class="admin__control-text">
            </div>
        </div>

        <div class="admin__field _required">

            <label class="admin__field-label">
                <span>Description</span>
            </label>

            <div class="admin__field-control">
                <textarea name="description" placeholder="Description" id="description" class="admin__control-text"></textarea>
            </div>
        </div><br/>


        <div class="admin__field _required">
            <label class="admin__field-label">
                <span>Shipping Address Information</span>
            </label>
            <div class="field">
                <div class="control">
                    <select name="shipping_address" id="shipping_address" data-myvalue="<?= $editEvent->getData('shipping_address')?>" style="border: 1px solid #adadad; width: 100%; height: 35px; background: white">
                        <option value=""><?= __('Shipping Address')  ?></option>
                        <?php if ($addressArr) {
                            foreach ($addressArr as $address) {
                                ?>
                                <option value="<?= $address['id'] ?>"><?= $address['name'] ?></option>
                            <?php  } }?>
                    </select>
                </div>
            </div>
        </div> <br>

        <p id="notify_validate" class="message message-error error" hidden></p>
    </div>

    <div id="<?= $block->escapeHtml($block->getId()) ?>" data-grid-id="<?= $block->escapeHtml($block->getId()) ?>">
        <?php else: ?>
            <?= $block->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
        <?php endif; ?>
        <?php $massActionAvailable = $block->getMassactionBlock() && $block->getMassactionBlock()->isAvailable() ?>
        <?php if ($block->getPagerVisibility() || $block->getExportTypes() || $block->getFilterVisibility() || $massActionAvailable): ?>
            <div class="admin__data-grid-header admin__data-grid-toolbar">
                <div class="admin__data-grid-header-row">
                    <?php if ($massActionAvailable): ?>
                        <?= $block->getMainButtonsHtml() ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>' : '' ?>
                    <?php endif; ?>
                    <?php if ($block->getExportTypes()): ?>
                        <div class="admin__data-grid-export">
                            <label
                                class="admin__control-support-text"
                                for="<?= $block->escapeHtml($block->getId()) ?>_export"><?= __('Export to:') ?>
                            </label>
                            <select name="<?= $block->escapeHtml($block->getId()) ?>_export"
                                    id="<?= $block->escapeHtml($block->getId()) ?>_export"
                                    class="admin__control-select">
                                <?php foreach ($block->getExportTypes() as $_type): ?>
                                    <option value="<?= $_type->getUrl() ?>">
                                        <?= $_type->getLabel() ?>
                                    </option>
                                <?php endforeach; ?>
                            </select>
                            <?= $block->getExportButtonHtml() ?>
                        </div>
                    <?php endif; ?>
                </div>

                <div class="admin__data-grid-header-row <?= $massActionAvailable ? '_massaction' : '' ?>">
                    <?php if ($massActionAvailable): ?>
                        <?= $block->getMassactionBlockHtml() ?>
                    <?php else: ?>
                        <?= $block->getMainButtonsHtml() ? '<div class="admin__filter-actions">' . $block->getMainButtonsHtml() . '</div>' : '' ?>
                    <?php endif; ?>
                    <?php $countRecords = $block->getCollection()->getSize(); ?>
                    <div class="admin__control-support-text">
                        <span id="<?= $block->escapeHtml($block->getHtmlId()) ?>-total-count" <?= $block->getUiId('total-count') ?>>
                            <?= $countRecords ?>
                        </span>
                        <?= __('records found') ?>
                        <span id="<?= $block->escapeHtml($block->getHtmlId()) ?>_massaction-count" class="mass-select-info _empty">
                            <strong data-role="counter">0</strong>
                            <span><?= __('selected') ?></span>
                        </span>
                    </div>

                    <?php if ($block->getPagerVisibility()): ?>
                        <div class="admin__data-grid-pager-wrap">
                            <select name="<?= $block->getVarNameLimit() ?>"
                                    id="<?= $block->escapeHtml($block->getHtmlId()) ?>_page-limit"
                                    onchange="<?= $block->getJsObjectName() ?>.loadByElement(this)"
                                    class="admin__control-select">
                                <option value="20"<?php if ($block->getCollection()->getPageSize() == 20): ?>
                                    selected="selected"<?php endif; ?>>20
                                </option>
                                <option value="30"<?php if ($block->getCollection()->getPageSize() == 30): ?>
                                    selected="selected"<?php endif; ?>>30
                                </option>
                                <option value="50"<?php if ($block->getCollection()->getPageSize() == 50): ?>
                                    selected="selected"<?php endif; ?>>50
                                </option>
                                <option value="100"<?php if ($block->getCollection()->getPageSize() == 100): ?>
                                    selected="selected"<?php endif; ?>>100
                                </option>
                                <option value="200"<?php if ($block->getCollection()->getPageSize() == 200): ?>
                                    selected="selected"<?php endif; ?>>200
                                </option>
                            </select>
                            <label for="<?= $block->escapeHtml($block->getHtmlId()) ?><?= $block->escapeHtml($block->getHtmlId()) ?>_page-limit"
                                   class="admin__control-support-text"><?= __('per page') ?></label>

                            <div class="admin__data-grid-pager">
                                <?php $_curPage = $block->getCollection()->getCurPage() ?>
                                <?php $_lastPage = $block->getCollection()->getLastPageNumber() ?>
                                <?php if ($_curPage > 1): ?>
                                    <button class="action-previous"
                                            type="button"
                                            onclick="<?= $block->getJsObjectName() ?>.setPage('<?= ($_curPage - 1) ?>');return false;">
                                        <span><?= __('Previous page') ?></span>
                                    </button>
                                <?php else: ?>
                                    <button type="button" class="action-previous disabled">
                                        <span><?= __('Previous page') ?></span></button>
                                <?php endif; ?>
                                <input type="text"
                                       id="<?= $block->escapeHtml($block->getHtmlId()) ?>_page-current"
                                       name="<?= $block->getVarNamePage() ?>"
                                       value="<?= $_curPage ?>"
                                       class="admin__control-text"
                                       onkeypress="<?= $block->getJsObjectName() ?>.inputPage(event, '<?= $_lastPage ?>')" <?= $block->getUiId('current-page') ?> />
                                <label class="admin__control-support-text"
                                       for="<?= $block->escapeHtml($block->getHtmlId()) ?>_page-current">
                                    <?= __('of %1', '<span>' . $block->getCollection()->getLastPageNumber() . '</span>') ?>
                                </label>
                                <?php if ($_curPage < $_lastPage): ?>
                                    <button type="button"
                                            title="<?= __('Next page') ?>"
                                            class="action-next"
                                            onclick="<?= $block->getJsObjectName() ?>.setPage('<?= ($_curPage + 1) ?>');return false;">
                                        <span><?= __('Next page') ?></span>
                                    </button>
                                <?php else: ?>
                                    <button type="button" class="action-next disabled">
                                        <span><?= __('Next page') ?></span></button>
                                <?php endif; ?>
                            </div>
                        </div>
                    <?php endif ?>
                </div>
            </div>
        <?php endif; ?>

        <div class="admin__data-grid-wrap admin__data-grid-wrap-static">
            <table class="data-grid" id="<?= $block->escapeHtml($block->getId()) ?>_table">
                <?php
                /* This part is commented to remove all <col> tags from the code. */
                /* foreach ($block->getColumns() as $_column): ?>
                <col <?= $_column->getHtmlProperty() ?> />
                <?php endforeach; */
                ?>
                <?php if ($block->getHeadersVisibility() || $block->getFilterVisibility()): ?>
                    <thead>
                    <?php if ($block->getHeadersVisibility()): ?>
                        <tr>
                            <?php foreach ($block->getColumns() as $_column): ?>
                                <?php if ($_column->getHeaderHtml() == '&nbsp;'): ?>
                                    <th class="data-grid-th" data-column="<?= $_column->getId() ?>"
                                        <?= $_column->getHeaderHtmlProperty() ?>>&nbsp;
                                    </th>
                                <?php else: ?>
                                    <?= $_column->getHeaderHtml() ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif; ?>
                    <?php if ($block->getFilterVisibility()): ?>
                        <tr class="data-grid-filters" data-role="filter-form">
                            <?php $i = 0;
                            foreach ($block->getColumns() as $_column): ?>
                                <td data-column="<?= $_column->getId() ?>" <?= $_column->getHeaderHtmlProperty() ?>>
                                    <?= $_column->getFilterHtml() ?>
                                </td>
                            <?php endforeach; ?>
                        </tr>
                    <?php endif ?>
                    </thead>
                <?php endif; ?>
                <?php if ($block->getCountTotals()): ?>
                    <tfoot>
                    <tr class="totals">
                        <?php foreach ($block->getColumns() as $_column): ?>
                            <th class="<?= $_column->getCssProperty() ?>">
                                <?= ($_column->hasTotalsLabel()) ? $_column->getTotalsLabel() : $_column->getRowField($_column->getGrid()->getTotals()) ?>
                            </th>
                        <?php endforeach; ?>
                    </tr>
                    </tfoot>
                <?php endif; ?>

                <tbody>
                <?php if (($block->getCollection()->getSize() > 0) && (!$block->getIsCollapsed())): ?>
                    <?php foreach ($block->getCollection() as $_index => $_item): ?>
                        <tr title="<?= $block->getRowUrl($_item) ?>"<?php if ($_class = $block->getRowClass($_item)): ?>
                            class="<?= $_class ?>"<?php endif; ?> ><?php
                            $i = 0;
                            foreach ($block->getColumns() as $_column):
                                if ($block->shouldRenderCell($_item, $_column)):
                                    $_rowspan = $block->getRowspan($_item, $_column);
                                    ?>
                                <td <?= ($_rowspan ? 'rowspan="' . $_rowspan . '" ' : '') ?>
                                    class="<?= $_column->getCssProperty() ?>
                                        <?= $_column->getId() == 'massaction' ? 'data-grid-checkbox-cell' : '' ?>">
                                    <?= (($_html = $_column->getRowField($_item)) != '' ? $_html : '&nbsp;') ?>
                                    </td><?php
                                    if ($block->shouldRenderEmptyCell($_item, $_column)):
                                        ?>
                                        <td colspan="<?= $block->getEmptyCellColspan($_item) ?>"
                                            class="last"><?= $block->getEmptyCellLabel() ?></td>
                                    <?php endif;
                                endif;
                            endforeach; ?>
                        </tr>
                        <?php if ($_multipleRows = $block->getMultipleRows($_item)): ?>
                            <?php foreach ($_multipleRows as $_i): ?>
                                <tr>
                                    <?php $i = 0;
                                    foreach ($block->getMultipleRowColumns($_i) as $_column): ?>
                                        <td class="<?= $_column->getCssProperty() ?>
                                        <?= $_column->getId() == 'massaction' ? 'data-grid-checkbox-cell' : '' ?>">
                                            <?= (($_html = $_column->getRowField($_i)) != '' ? $_html : '&nbsp;') ?>
                                        </td>
                                    <?php endforeach; ?>
                                </tr>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <?php if ($block->shouldRenderSubTotal($_item)): ?>
                            <tr class="subtotals">
                                <?php $i = 0;
                                foreach ($block->getSubTotalColumns() as $_column): ?>
                                    <td class="<?= $_column->getCssProperty() ?>
                                           <?= $_column->getId() == 'massaction' ? 'data-grid-checkbox-cell' : '' ?>">
                                        <?=($_column->hasSubtotalsLabel() ? $_column->getSubtotalsLabel() :
                                            $_column->getRowField($block->getSubTotalItem($_item))
                                        );
                                        ?>
                                    </td>
                                <?php endforeach; ?>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                <?php elseif ($block->getEmptyText()): ?>
                    <tr class="data-grid-tr-no-data">
                        <td class="<?= $block->getEmptyTextClass() ?>"
                            colspan="<?= $numColumns ?>">
                            <?= $block->getEmptyText() ?>
                        </td>
                    </tr>
                <?php endif; ?>
                </tbody>
            </table>

        </div>
        <?php if ($block->canDisplayContainer()): ?>
    </div>
    <script>
        var deps = [];

        <?php if ($block->getDependencyJsObject()): ?>
        deps.push('uiRegistry');
        <?php endif; ?>

        <?php if (strpos($block->getRowClickCallback(), 'order.') !== false): ?>
        deps.push('Magento_Sales/order/create/form')
        <?php endif; ?>

        deps.push('mage/adminhtml/grid');

        <?php if (is_array($block->getRequireJsDependencies())): ?>
        <?php foreach ($block->getRequireJsDependencies() as $dependency): ?>
        deps.push('<?= $dependency ?>');
        <?php endforeach; ?>
        <?php endif; ?>

        require(deps, function (<?= ($block->getDependencyJsObject() ? 'registry' : '') ?>) {
            <?php //TODO: getJsObjectName and getRowClickCallback has unexpected behavior. Should be removed ?>

            //<![CDATA[
            <?php if ($block->getDependencyJsObject()): ?>
            registry.get('<?= $block->getDependencyJsObject() ?>', function (<?= $block->getDependencyJsObject() ?>) {
                <?php endif; ?>

                <?= $block->getJsObjectName() ?> = new varienGrid(<?= /* @noEscape */ $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getId()) ?>, '<?= $block->getGridUrl() ?>', '<?= $block->getVarNamePage() ?>', '<?= $block->getVarNameSort() ?>', '<?= $block->getVarNameDir() ?>', '<?= $block->getVarNameFilter() ?>');
                <?= $block->getJsObjectName() ?>.
                useAjax = '<?= $block->getUseAjax() ?>';
                <?php if ($block->getRowClickCallback()): ?>
                <?= $block->getJsObjectName() ?>.
                rowClickCallback = <?= $block->getRowClickCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getCheckboxCheckCallback()): ?>
                <?= $block->getJsObjectName() ?>.
                checkboxCheckCallback = <?= $block->getCheckboxCheckCallback() ?>;
                <?php endif; ?>
                <?php if ($block->getRowInitCallback()): ?>
                <?= $block->getJsObjectName() ?>.
                initRowCallback = <?= $block->getRowInitCallback() ?>;
                <?= $block->getJsObjectName() ?>.
                initGridRows();
                <?php endif; ?>
                <?php if ($block->getMassactionBlock() && $block->getMassactionBlock()->isAvailable()): ?>
                <?= $block->getMassactionBlock()->getJavaScript() ?>
                <?php endif ?>
                <?= $block->getAdditionalJavaScript() ?>

                <?php if ($block->getDependencyJsObject()): ?>
            });
            <?php endif; ?>
            //]]>

        });
    </script>
    <script type="text/x-magento-init">
    {
        "#giftregistry_add_form": {
            "validation": {},
            "Magenest_GiftRegistry/js/giftregistry/add_gift": {
                "address_url": "<?= $block->getUrl('gift_registry/customer/address'); ?>"
            }
        }
    }
</script>
    <script>
        require([
            'jquery',
            'Magento_Ui/js/modal/modal',
            'Magento_Ui/js/modal/alert'
        ], function ($, modal, alert) {
            $('body').on('click', '#add_gift', function () {
                var dataForm = $('#popup');
                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Enter Add Point ',
                    buttons: [{
                        text: 'Add',
                        class: 'action primary',
                        attr: {id: 'btn-apply'},
                        click: function () {
                            var notify = $('#notify_validate');
                            var firstName = $('#firstName').val();
                            var lastName = $('#lastName').val();
                            var email = $('#email').val();
                            var privacy = $('#select-privacy').val();
                            var show_in_search = $('#show_in_search').val();
                            var type = $('#event_type').val();
                            var title = $('#event_title').val();
                            var date = $('#date').val();
                            var description = $('#description').val();
                            var shipping_address = $('#shipping_address').val();

                            var formData = new FormData();
                            var formKey = window.FORM_KEY;
                            formData.append('customer_id', '<?= $block->getCustomerId()?>');
                            formData.append('firstName', firstName);
                            formData.append('lastName', lastName);
                            formData.append('email', email);
                            formData.append('privacy', privacy);
                            formData.append('show_in_search', show_in_search);
                            formData.append('type', type);
                            formData.append('title', title);
                            formData.append('date', date);
                            formData.append('description', description);
                            formData.append('shipping_address', shipping_address);
                            formData.append('form_key', formKey);

                            if (firstName !== '' && lastName !== '' && email !== '' && type !== '' && title !== '' && date !== '' && description !== '') {
                                notify.hide();
                                $.ajax({
                                    url: '<?= $block->getAddPointUrl()?>',
                                    data: formData,
                                    processData: false,
                                    contentType: false,
                                    showLoader: true,
                                    type: 'POST',
                                    dataType: 'json',
                                    success: function (response) {
                                        if (response.success === true) {
                                            var resText;
                                            if (response.depleted === true) {
                                                resText = 'More failures'
                                            } else {
                                                resText = 'You have successfully added';
                                            }
                                            popup.closeModal();
                                            alert({
                                                title: 'Success',
                                                content: resText,
                                                buttons: [{
                                                    text: $.mage.__('OK'),
                                                    class: 'action-primary action-accept',

                                                    /**
                                                     * Click handler.
                                                     */
                                                    click: function () {
                                                        this.closeModal(true);
                                                        $('#transaction_tab').data('gridObject').reload();
                                                    }
                                                }]
                                            });
                                        } else {
                                            popup.closeModal();
                                            alert({
                                                title: 'Fail',
                                                content: 'Somethings is errors. Please try again',
                                                actions: {
                                                    always: function () {
                                                    }
                                                }
                                            });
                                        }
                                    }
                                });
                            } else {
                                notify.html('Please complete the information');
                                notify.show();
                            }
                        }
                    }, {
                        text: 'Exit',
                        class: '',
                        click: function () {
                            this.closeModal();
                        }
                    }]
                };
                var popup = modal(options, dataForm);
                popup.openModal();
            });
        });
    </script>
<?php endif; ?>
<?php endif ?>
