<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * Edit customer address template
 *
 * @var $block \Magenest\GiftRegistry\Block\Customer\Registry\Shipping\Address
 */
$regionArray = $block->getRegionData();
$countryList = array_unique(array_column($regionArray, 'country_id'));
?>
<form class="form-address-edit" data-mage-init='{"validation": {}}' autocomplete="off" data-role="form-address-new"
      action="<?= $block->getSaveUrl() ?>" method="post" id="form-address" enctype="multipart/form-data"
      data-hasrequired="<?= __('* Required Fields') ?>">
  <fieldset class="fieldset">
    <legend class="legend"><span><?= __('Contact Information') ?></span></legend>
    <br>
    <?= $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="success_url" value="<?= $block->getSuccessUrl() ?>">
    <input type="hidden" name="error_url" value="<?= $block->getErrorUrl() ?>">
    <?= $block->getNameBlockHtml() ?>
    <div class="field company">
      <label class="label" for="company"><span><?= __('Company') ?></span></label>
      <div class="control">
        <input type="text" name="company" id="company" title="<?= __('Company') ?>"
               value="<?= $block->escapeHtml($block->getAddress()->getCompany()) ?>"
               class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('company') ?>">
      </div>
    </div>
    <div class="field telephone required">
      <label class="label " for="telephone"><span><?= __('Phone Number') ?></span></label>
      <div class="control">
        <input type="text" data-validate="{required:true,'validate-number':true}" name="telephone"
               value="<?= $block->escapeHtml($block->getAddress()->getTelephone()) ?>"
               title="<?= __('Phone Number') ?>"
               class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('telephone') ?>"
               id="telephone">
      </div>
      <label id="error-phone" style="color:red"
             hidden><?= __("Seem like you have typed a wrong phone number!") ?></label>
    </div>
    <div class="field fax">
      <label class="label" for="fax"><span><?= __('Fax') ?></span></label>
      <div class="control">
        <input type="text" name="fax" id="fax" title="<?= __('Fax') ?>"
               value="<?= $block->escapeHtml($block->getAddress()->getFax()) ?>"
               class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('fax') ?>">
      </div>
    </div>
  </fieldset>
  <fieldset class="fieldset">
    <legend class="legend"><span><?= __('Address') ?></span></legend>
    <br>
    <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>
    <div class="field street required">
      <label for="street_1" class="label"><span><?= __('Street Address') ?></span></label>
      <div class="control">
        <input type="text" data-validate="{required:true}" name="street[]"
               value="<?= $block->escapeHtml($block->getStreetLine(1)) ?>"
               title="<?= __('Street Address') ?>" id="street_1"
               class="input-text <?= $_streetValidationClass ?>"/>
        <div class="nested">
          <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
          <?php for ($_i = 1, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i < $_n; $_i++): ?>
            <div class="field additional">
              <label class="label" for="street_<?= $_i + 1 ?>">
                <span><?= __('Street Address %1', $_i + 1) ?></span>
              </label>
              <div class="control">
                <input type="text" name="street[]"
                       value="<?= $block->escapeHtml($block->getStreetLine($_i + 1)) ?>"
                       title="<?= __('Street Address %1', $_i + 1) ?>" id="street_<?= $_i + 1 ?>"
                       class="input-text <?= $_streetValidationClass ?>">
              </div>
            </div>
          <?php endfor; ?>
        </div>
      </div>
    </div>

    <?php if ($this->helper('Magento\Customer\Helper\Address')->isVatAttributeVisible()) : ?>
      <div class="field taxvat">
        <label class="label" for="vat_id"><span><?= __('VAT Number') ?></span></label>
        <div class="control">
          <input type="text" name="vat_id" value="<?= $block->escapeHtml($block->getAddress()->getVatId()) ?>"
                 title="<?= __('VAT Number') ?>"
                 class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('vat_id') ?>"
                 id="vat_id">
        </div>
      </div>
    <?php endif; ?>
    <div class="field city required">
      <label class="label" for="city"><span><?= __('City') ?></span></label>
      <div class="control">
        <input type="text" data-validate="{required:true}" name="city"
               value="<?= $block->escapeHtml($block->getAddress()->getCity()) ?>"
               title="<?= __('City') ?>"
               class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city') ?>"
               id="city">
      </div>
    </div>
    <div class="field region required">
      <label class="label" for="region_id"><span><?= __('State/Province') ?></span></label>
      <div class="control">
        <input type="text" id="region" name="region" value="<?= $block->escapeHtml($block->getRegion()) ?>"
               title="<?= __('State/Province') ?>"
               class="input-text <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region') ?>"<?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : ''; ?>/>
        <?= $block->getAllRegionSelect() ?>
      </div>
    </div>
    <div class="field zip required">
      <label class="label" for="zip"><span><?= __('Zip/Postal Code') ?></span></label>
      <div class="control">
        <input type="text" data-validate="{required:true}" name="postcode"
               value="<?= $block->escapeHtml($block->getAddress()->getPostcode()) ?>"
               title="<?= __('Zip/Postal Code') ?>" id="zip"
               class="input-text validate-zip-international <?= $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode') ?>">
      </div>
    </div>
    <div class="field country required">
      <label class="label" for="country"><span><?= __('Country') ?></span></label>
      <div class="control">
        <?= $block->getCountryHtmlSelect() ?>
      </div>
    </div>

    <?php if ($block->isDefaultBilling()): ?>
      <div class="field note default"><?= __('Default Billing Address') ?></div>
    <?php elseif ($block->canSetAsDefaultBilling()): ?>
      <div class="field choice set billing">
        <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
        <label class="label"
               for="primary_billing"><span><?= __('Use as my default billing address') ?></span></label>
      </div>
    <?php else: ?>
      <input type="hidden" name="default_billing" value="1"/>
    <?php endif; ?>

    <?php if ($block->isDefaultShipping()): ?>
      <div class="field note default"><?= __('Default Shipping Address') ?></div>
    <?php elseif ($block->canSetAsDefaultShipping()): ?>
      <div class="field choice set shipping">
        <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
        <label class="label" for="primary_shipping"><span><?= __('Use as my default shipping address') ?></span></label>
      </div>
    <?php else: ?>
      <input type="hidden" name="default_shipping" value="1">
    <?php endif; ?>
  </fieldset>
  <div class="actions-toolbar">
    <div class="primary">
      <button type="button" id="save-address" class="action save primary" data-action="save-address"
              title="<?= __('Save Address') ?>">
        <span><?= __('Save Address') ?></span>
      </button>
      <span class="loading" data-role="loading-for-address">&nbsp; &nbsp; &nbsp; &nbsp;</span>
    </div>
    <div class="secondary">
      <a class="action back"
         href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= __('Go back') ?></span></a>
    </div>
  </div>
</form>
<script>
  require(['jquery'], function ($) {
    let regionList = <?= $block->jsonEncode($regionArray) ?>;
    let countryList = <?= $block->jsonEncode($countryList) ?>;

    selectDisplay();
    $(document).on('change', '#country', selectDisplay);

    function selectDisplay() {
      let selectedCountry = $('#country').val();
      for (let country in countryList) {
        if (countryList[country] === selectedCountry) {
          $("#region").hide().val("");
          $("#region_id").show().val("");
          $("#region_id > option").each(filter);
          return;
        }
      }
      $("#region").show().val("");
      $("#region_id").hide().val("");
    }

    function filter() {
      if (this.value && regionList[this.value - 1]["country_id"] !== $('#country').val()) {
        this.style.display = 'none';
        this.disabled = true;
      } else {
        this.style.display = 'inline-block';
        this.disabled = false;
      }
    }
  })
</script>
