<?php

/**
 * Created by Magenest.
 * User: trongpq
 * Date: 3/2/18
 * Time: 10:27
 * Email: trongpq@magenest.com
 */

namespace Magenest\GiftRegistry\Ui\DataProvider\Order;

use Magenest\GiftRegistry\Model\ResourceModel\Tran\Collection;
use Magento\Framework\Api\Filter;
use Magento\Framework\Api\FilterBuilder;
use Magento\Framework\Api\Search\ReportingInterface;
use Magento\Framework\Api\Search\SearchCriteriaBuilder;
use Magento\Framework\Api\Search\SearchResultInterface;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider;
use Magento\Sales\Model\OrderFactory;

/**
 * Class TransactionDataProvider
 * @package Magenest\GiftRegistry\Ui\DataProvider\Order
 */
class TransactionDataProvider extends DataProvider
{

    /**
     * @var OrderFactory
     */
    protected $orderFactory;

    /**
     * @var Collection
     */
    protected $collection;

    /**
     * TransactionDataProvider constructor.
     * @param string $name
     * @param string $primaryFieldName
     * @param string $requestFieldName
     * @param ReportingInterface $reporting
     * @param SearchCriteriaBuilder $searchCriteriaBuilder
     * @param RequestInterface $request
     * @param FilterBuilder $filterBuilder
     * @param OrderFactory $order
     * @param Collection $collectionFactory
     * @param array $meta
     * @param array $data
     */
    public function __construct(
        $name,
        $primaryFieldName,
        $requestFieldName,
        ReportingInterface $reporting,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        RequestInterface $request,
        FilterBuilder $filterBuilder,
        OrderFactory $order,
        Collection $collectionFactory,
        array $meta = [],
        array $data = []
    ) {
        parent::__construct($name, $primaryFieldName, $requestFieldName, $reporting, $searchCriteriaBuilder, $request, $filterBuilder, $meta, $data);
        $this->orderFactory = $order;
        $this->collection = $collectionFactory;
    }

    /**
     * @return SearchResultInterface
     */
    public function getSearchResult()
    {
        $result = parent::getSearchResult(); // TODO: Change the autogenerated stub
        $result->getSelect()->join(
            ["sales_order" => $result->getTable("sales_order_grid")],
            "main_table.order_id = sales_order.entity_id",
            ["customer_email","billing_name","created_at","increment_id"]
        );

        return $result;
    }

    /**
     * @param Filter $filter
     * @return mixed|void
     */
    public function addFilter(Filter $filter)
    {
        if ($filter->getField()=="status") {
            $filter->setField("main_table.status");
        }
        parent::addFilter($filter); // TODO: Change the autogenerated stub
    }
}
